### PR TITLE
Update Google Play & F-Droid Badges

### PR DESCRIPTION
**Pull request by SusanKenneth**

### CODE REVIEW

**Comment by SusanKenneth** [comment]
Hi @nbossard,
thanks for your amazing Android app! 😎
I felt free to update the Google Play & F-Droid badges and added two shields (Travis & GitHub Downloads).
Maybe you can add [Snyk](https://snyk.io/), [CODEBEAT](https://codebeat.co/) and [Crowdin](https://crowdin.com/) shields?

**Comment by nbossard** [comment]
Great idea, thanks for your suggestions, I read more about shields and I merge your pull request.
Merry christmas

**Comment by nbossard** [comment]
Ok this looks great, 
You should also have removed local images for playstore and f-droid, cause they are now useless.
I do it now.
Don't hesitate to add shield for crowdin, I will look at snyk and codebeat that I don't know yet.

**Comment by nbossard** [comment]
Seems that the link on the number of download leads to a 404, where should it drive user ?

**Comment by SusanKenneth** [comment]
I fixed that with https://github.com/nbossard/packlist/pull/69, sorry 😅

**Comment by SusanKenneth** [comment]
You can signup at [crowdin](https://crowdin.com/) and use the [GitHub integration](https://support.crowdin.com/github-integration/). Then you will find the Markdown for the badge there. After the setup, I can test it by doing a German translation if you like. 😀

**Pull request merged**
